### ISSUE TITLE
Power jack tabs currently have hole footprints rather than slots

### ISSUE THREAD

**Issue by bigjosh** [bigjosh/Airboat-PCB#7]
This is because (1) Otherplan can not current cut slots for no good reason, (2) Sunstone charges extra for slots. 

Current footprints work fine, but might want to switch back before production.

**Comment by DameRebeca** [comment]
Work fine - then okay with me.  Suggest, no need to change back, leave as is.

**Comment by bigjosh** [comment]
They do work fine, but we had a factory who really didn't like them. Once we get a beta board, I'll probably switch back to slots just to avoid any conflict.

**Comment by bigjosh** [comment]
Power jack replace with SMT version so no more holes.
